blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home_view

urlpatterns = [
   path('', home_view),
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

blog/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('questions/', views.question_list, name='question_list'),
]
urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),

]

blog/polls/models.py
from django.db import models
QUESTION_TYPES = (
    (1, 'otwarte'),
    (2, 'zamknięte')
)

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    type = models.IntegerField(choices=QUESTION_TYPES, default=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Answer(models.Model):
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)

blog/pvchat/models.py
from django.db import models


class Message(models.Model):
    message_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.message_text
        
class Like(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.message

blog/blog/views.py
from django.shortcuts import render

def home_view(request):
   # print(request)
   # print(request.user)

   
   return render(request, 'home.html')

blog/polls/views.py
from .models import Question
from django.shortcuts import render, get_object_or_404

def question_list(request):
   questions = Question.objects.all()
   return render(request, 'polls/question_list.html', {'questions': questions})

def question_detail(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/question_detail.html', {'question': question})

blog/pvchat/views.py
from django.shortcuts import render

# Create your views here.

blog/polls/templates/polls/question_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'polls/style.css'%}">
</head>
<body>
<div>
   <table>
       <tr>
           <th>Id pytania</th>
           <th>Treść</th>
           <th>Data publikacji</th>
       </tr>
       {% for question in questions %}
           <tr>
               <td>{{ question.id}}</td>
               <td><a href="{% url 'polls:question_detail' question.id %}">
                      {{ question.question_text }}</a>
               </td>
               <td>{{ question.pub_date}}</td>
           </tr>

       {% endfor %}
   </table>
</div>
</body>
</html>

blog/templates/home.html
<h1> Strona główna </h1>

<!-- {{ user.is_authenticated }} -->

{% if user.is_authenticated %}
   <p>Cześć {{ user }}</p>
{% else %}
     <p>Nie jestes zalogowany</p>

{% endif %}
<button><a href="{% url 'polls:question_list'%}">Pytania</a></button>

blog/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<h1>{{ question.pub_date }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <ul>
       <li>{{ choice.choice_text }} ({{ choice.votes }}) </li>
    </ul>
{% endfor %}
</ul>
<ul>
{% for answer in question.answer_set.all %}
    <ul>
       <li>{{ answer.answer_text }} </li>
    </ul>
{% endfor %}
</ul>open

blog/templates/polls/question_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
<div>
    <table>
        <tr>
            <th>Id pytania</th>
            <th>Treść</th>
            <th>Data publikacji</th>
        </tr>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td><a href="{% url 'polls:question_detail' question.id %}">

                {{ question.question_text }}</a>
                </td>
                <td>{{question.pub_date}}</td>
                <td>{{question.type}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} ({{choice.votes}})</li>
{% endfor %}
</ul>

templates/polls/question_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'polls/style.css'%}">
</head>
<body>
<div>
   <table>
       <tr>
           <th>Id pytania</th>
           <th>Treść</th>
           <th>Data publikacji</th>
       </tr>
       {% for question in questions %}
           <tr>
               <td>{{ question.id}}</td>
               <td><a href="{% url 'polls:question_detail' question.id %}">
                      {{ question.question_text }}</a>
               </td>
               <td>{{ question.pub_date }}</td>
               <td>{{ question.type }}</td>
           </tr>

       {% endfor %}
   </table>
</div>
</body>
</html>